CREATE TABLE [dbo].[agentlogin_test] (
    [UserID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [UserCode]           VARCHAR (10)    NULL,
    [UserName]           VARCHAR (500)   NULL,
    [Password]           VARCHAR (300)   NULL,
    [FirstName]          VARCHAR (150)   NULL,
    [LastName]           VARCHAR (150)   NULL,
    [InsertedDate]       DATETIME        NULL,
    [IsActive]           TINYINT         NULL,
    [MobileNumber]       VARCHAR (100)   NULL,
    [NewsLetter]         TINYINT         NULL,
    [Address]            VARCHAR (500)   NULL,
    [City]               VARCHAR (100)   NULL,
    [Country]            VARCHAR (100)   NULL,
    [Pincode]            VARCHAR (10)    NULL,
    [DrivingLicenceNo]   VARCHAR (20)    NULL,
    [HomeNo]             VARCHAR (20)    NULL,
    [Province]           VARCHAR (50)    NULL,
    [BookingCountry]     VARCHAR (2)     NULL,
    [IsB2BAgent]         BIT             NULL,
    [AgentApproved]      BIT             NULL,
    [SessionID]          VARCHAR (50)    NULL,
    [AgentBalance]       MONEY           NULL,
    [ParentAgentID]      BIGINT          NULL,
    [ResetPwdFlag]       BIT             NULL,
    [AccessFlag]         INT             NULL,
    [Currency]           VARCHAR (10)    NULL,
    [UserTypeID]         INT             NULL,
    [IsFlightSelected]   BIT             NULL,
    [IsHotelSelected]    BIT             NULL,
    [BalanceUpdateDate]  DATETIME        NULL,
    [FareType]           VARCHAR (MAX)   NULL,
    [NewCurrency]        VARCHAR (MAX)   NULL,
    [TicketFormate]      VARCHAR (10)    NULL,
    [AutoTicketing]      BIT             NULL,
    [GhostTrack]         BIT             NULL,
    [ROE]                DECIMAL (18, 6) NULL,
    [ModifiedOn]         DATETIME2 (7)   NULL,
    [ModifiedBy]         INT             NULL,
    [NewSelfBalance]     BIT             NULL,
    [OutstandingBalance] MONEY           NULL,
    [ActiveFlag]         BIT             NULL,
    [GroupId]            INT             NULL,
    [EncryptedPassword]  NVARCHAR (200)  NULL,
    [UserDeviceID]       VARCHAR (100)   NULL,
    [UserDeviceIDTime]   DATETIME        NULL,
    [OTPGenerated]       VARCHAR (50)    NULL,
    [OTPTime]            DATETIME        NULL,
    [LoginAttempt]       INT             NULL,
    [AttemptNo]          INT             NULL,
    [AttemptedDate]      DATETIME        NULL,
    [Logo]               VARCHAR (MAX)   NULL,
    [NoERP]              BIT             NULL,
    [AgentLogoNew]       VARCHAR (MAX)   NULL,
    [HotelBookAccess]    BIT             NULL,
    [OTPRequired]        BIT             NULL,
    [LastLoginDate]      DATETIME        NULL,
    [CreatedBy]          INT             NULL,
    [ForeColorCode]      VARCHAR (10)    NULL,
    [BackColorCode]      VARCHAR (10)    NULL,
    [ParentAgencyID]     INT             NULL,
    [LoginFromCountry]   VARCHAR (MAX)   NULL,
    [SubUserEmail]       VARCHAR (500)   NULL,
    [PasswordExpiryDate] DATETIME        NULL,
    [PasswordEncrypt]    VARCHAR (550)   NULL,
    [BalanceFetch]       VARCHAR (100)   NULL,
    [StationID]          VARCHAR (50)    NULL,
    [password_encrypted] VARBINARY (MAX) NULL,
    new_column   varchar(100) null
);

